---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: flux-system
spec:
  chart: reflector
  interval: 6h0m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: emberstack
  version: 7.1.x
