service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.59.150
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443