---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  chartRef:
    kind: HelmChart
    name: reflector
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: reflector
  targetNamespace: reflector
