---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: gateway
  namespace: flux-system
spec:
  chart: gateway
  interval: 1m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: istio
  version: 1.24.x
