---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/weaveworks/weave-gitops.git
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/gitops-server
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: weave-gitops
  targetNamespace: weave-gitops
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$vwMbErTlVkVAZvk5cTi2zuqG2AS1y3Xsv5okZGSleQaTIEK7gPiiy
      username: admin
    fullnameOverride: weave-gitops
