---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: main
  url: https://github.com/weaveworks/weave-gitops.git
