---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chartRef:
    kind: HelmChart
    name: cert-manager
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    crds:
      enabled: true
    fullnameOverride: cert-manager
