---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chartRef:
    kind: HelmChart
    name: metallb
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: metallb
  targetNamespace: metallb-system
  values:
    fullnameOverride: metallb
    speaker:
      tolerateMaster: false
